[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clippy"]

[tasks.audit]
command = "cargo"
args = ["audit"]
dependencies = ["test"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["audit"]

[tasks.all]
dependencies = [
    "format",
    "clean",
    "clippy",
    "test",
    "audit",
    "build"
]